# Undistorts the two videos to check intrinsic calibration results
save_name: undist
global:
  video_name: "video6.mp4"
  camera_names: [ "nothing", "iphone" ]
  paths:
    originals: "resources/videos/originals"
  coords:
    world_lane: [ [ 0, 0, 0 ], [ 19, 0, 0 ], [ 19, -1.07, 0 ], [ 0, -1.07, 0 ] ]
  ball_radius: 0.1091
  visualization: True
pipeline:
  - name: intrinsic
    type: load
    params: {
      images_path: "resources/calibration"
    }
  - name: video_undistortion
    type: execute
    params: {
      save_path: "resources/videos/undistorted"
    }